-- as user system
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
CREATE USER svyeetuser IDENTIFIED BY svyeet123456;
GRANT CONNECT, RESOURCE, DBA TO svyeetuser;
GRANT unlimited TABLESPACE TO svyeetuser;
GRANT CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE TO svyeetuser;
CREATE TABLESPACE tbs_svyeet datafile 'tbs_svyeet_01.dat' SIZE 100M ONLINE;
ALTER USER svyeetuser DEFAULT TABLESPACE tbs_svyeet;
ALTER USER svyeetuser quota unlimited ON tbs_svyeet;
SELECT * FROM dba_users WHERE USERNAME = 'SVYEETUSER';

-- as user svyeetuser
DROP TABLE teams_sponsors;
DROP TABLE sponsors;
DROP TABLE matches;
DROP TABLE venues;
DROP TABLE members_teams_types;
DROP TABLE types;
DROP TABLE members;
DROP TABLE teams;
DROP TABLE leagues;
DROP TABLE sports;



-- CREATE TABLE



CREATE TABLE sports (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    title VARCHAR2(255) NOT NULL,
    CONSTRAINT pk_sports PRIMARY KEY (id)
);

CREATE TABLE leagues (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    title VARCHAR2(255) NOT NULL,
    priority NUMBER NOT NULL,
    sport_id NUMBER NOT NULL,
    CONSTRAINT pk_leagues PRIMARY KEY (id),
    CONSTRAINT fk_leagues_sports FOREIGN KEY (sport_id) REFERENCES sports(id)
);

CREATE TABLE teams (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    title VARCHAR2(255) NOT NULL,
    league_id NUMBER NOT NULL,
    CONSTRAINT pk_teams PRIMARY KEY (id),
    CONSTRAINT fk_teams_leagues FOREIGN KEY (league_id) REFERENCES leagues(id)
);

CREATE TABLE members (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    firstname VARCHAR2(255) NOT NULL,
    lastname VARCHAR2(255) NOT NULL,
    date_of_birth DATE,
    sex CHAR DEFAULT 'n',
    CONSTRAINT pk_members PRIMARY KEY (id)
);

CREATE TABLE types (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    title VARCHAR2(255) NOT NULL, 
    CONSTRAINT pk_types PRIMARY KEY (id)
);

CREATE TABLE members_teams_types (
    member_id NUMBER NOT NULL,
    team_id NUMBER,
    type_id NUMBER,
    CONSTRAINT fk_members_teams_types_members FOREIGN KEY (member_id) REFERENCES members(id),
    CONSTRAINT fk_members_teams_types_teams FOREIGN KEY (team_id) REFERENCES teams(id), 
    CONSTRAINT fk_members_teams_types_types FOREIGN KEY (type_id) REFERENCES types(id), 
    CONSTRAINT uq_members_teams_types UNIQUE(member_id, team_id, type_id)
);

CREATE TABLE venues (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    title VARCHAR2(255) NOT NULL,
    address VARCHAR2(255),
    CONSTRAINT pk_venues PRIMARY KEY (id)
);

CREATE TABLE matches (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    datetime TIMESTAMP NOT NULL,
    is_homegame NUMBER(1,0) DEFAULT 1 NOT NULL,
    opponend VARCHAR2(255) NOT NULL,
    result VARCHAR2(255),
    venue_id NUMBER NOT NULL,
    team_id NUMBER NOT NULL,
    CONSTRAINT pk_matches PRIMARY KEY (id),
    CONSTRAINT fk_matches_venues FOREIGN KEY (venue_id) REFERENCES venues(id),
    CONSTRAINT fk_matches_teams FOREIGN KEY (team_id) REFERENCES teams(id)
);

CREATE TABLE sponsors (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    title VARCHAR2(255) NOT NULL,
    CONSTRAINT pk_sponsors PRIMARY KEY (id)
);

CREATE TABLE teams_sponsors (
    team_id NUMBER NOT NULL,
    sponsor_id NUMBER NOT NULL,
    CONSTRAINT fk_teams_sponsors_teams FOREIGN KEY (team_id) REFERENCES teams(id), 
    CONSTRAINT fk_teams_sponsors_sponsors FOREIGN KEY (sponsor_id) REFERENCES sponsors(id),
    CONSTRAINT uq_teams_sponsors UNIQUE(team_id, sponsor_id)
);


CREATE TABLE exception_logging (
	id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	log_date TIMESTAMP NOT NULL,
	log_message VARCHAR2(255) NOT NULL,
	error_stack VARCHAR2(255) NOT NULL,
	error_code NUMBER NOT NULL,
	CONSTRAINT pk_exception_logging PRIMARY KEY (id)
);

-- INSERT



INSERT INTO sports (title) VALUES ('Fußball');
INSERT INTO sports (title) VALUES ('Handball');
INSERT INTO sports (title) VALUES ('Basketball');

INSERT INTO leagues (title, priority, sport_id) VALUES ('Bundesliga', 1, 1);
INSERT INTO leagues (title, priority, sport_id) VALUES ('Admiral Basketball Superliga', 1, 3);
INSERT INTO leagues (title, priority, sport_id) VALUES ('Regionalliga', 3, 1);
INSERT INTO leagues (title, priority, sport_id) VALUES ('Handball Liga Austria', 1, 2);
INSERT INTO leagues (title, priority, sport_id) VALUES ('2. Liga', 2, 1);
INSERT INTO leagues (title, priority, sport_id) VALUES ('Women Handball Austria', 1, 2);

INSERT INTO teams (title, league_id) VALUES ('FC Yeet', 1);
INSERT INTO teams (title, league_id) VALUES ('FC Yeet B', 5);
INSERT INTO teams (title, league_id) VALUES ('Yeet Globetrotters', 2);
INSERT INTO teams (title, league_id) VALUES ('FC Yeet Youngsters', 3);
INSERT INTO teams (title, league_id) VALUES ('WHA Yeet', 6);
INSERT INTO teams (title, league_id) VALUES ('HLA Yeet', 4);

INSERT INTO members (firstname, lastname, date_of_birth, sex) 
VALUES ('Michael', 'Jordan', TO_DATE('1963-02-17', 'yyyy-mm-dd'), 'm');
INSERT INTO members (firstname, lastname) 
VALUES ('Max', 'Muster');
INSERT INTO members (firstname, lastname, date_of_birth, sex) 
VALUES ('Josef', 'Koch', TO_DATE('1997-10-26', 'yyyy-mm-dd'), 'm');
INSERT INTO members (firstname, lastname, sex) VALUES ('Daniel', 'Krottendorfer', 'm');
INSERT INTO members (firstname, lastname, sex) VALUES ('Leo', 'Gruber', 'm');

INSERT INTO types (title) VALUES ('Player');
INSERT INTO types (title) VALUES ('Coach');
INSERT INTO types (title) VALUES ('President');

INSERT INTO members_teams_types (member_id, team_id, type_id) VALUES (1, 3, 1);
INSERT INTO members_teams_types (member_id, team_id, type_id) VALUES (2, 3, 2);
INSERT INTO members_teams_types (member_id, type_id) VALUES (3, 3);
INSERT INTO members_teams_types (member_id, type_id) VALUES (4, 3);
INSERT INTO members_teams_types (member_id, type_id) VALUES (5, 3);

INSERT INTO venues (title, address) 
VALUES ('Ernst-Happel-Stadion', 'Meiereistraße 7, 1020 Wien');
INSERT INTO venues (title, address) 
VALUES ('FH Technikum Wien', 'Höchstädtplatz 6, 1200 Wien');

INSERT INTO matches (datetime, opponend, venue_id, team_id)
VALUES (TIMESTAMP '2019-12-24 12:00:00', 'Xion Dukes Klosterneuburg', 1, 3);
INSERT INTO matches (datetime, is_homegame, opponend, venue_id, team_id)
VALUES (TIMESTAMP '2019-12-31 12:00:00', 0, 'BC Zepter Vienna', 2, 3);
INSERT INTO matches (datetime, is_homegame, opponend, result, venue_id, team_id)
VALUES (TIMESTAMP '2019-11-01 12:00:00', 1, 'SK Rapid Wien', '2:0', 1, 1);

INSERT INTO sponsors (title) VALUES ('Apple');
INSERT INTO sponsors (title) VALUES ('Google');
INSERT INTO sponsors (title) VALUES ('Amazon');

INSERT INTO teams_sponsors (team_id, sponsor_id) VALUES (3, 1);
INSERT INTO teams_sponsors (team_id, sponsor_id) VALUES (3, 2);
INSERT INTO teams_sponsors (team_id, sponsor_id) VALUES (1, 3);
INSERT INTO teams_sponsors (team_id, sponsor_id) VALUES (1, 2);



-- SELECTS Views ?



SELECT sports.title AS "Sport", leagues.title AS "League" FROM leagues 
INNER JOIN sports ON leagues.sport_id = sports.id
ORDER BY sports.id, leagues.priority;

SELECT teams.title AS "Team", sports.title AS "Sport", leagues.title AS "League" FROM teams 
INNER JOIN leagues ON teams.league_id = leagues.id
LEFT JOIN sports ON leagues.sport_id = sports.id
ORDER BY sports.id, leagues.priority;

SELECT members.firstname AS "Firstname", members.lastname AS "Lastname", 
members.sex AS "Sex", TO_CHAR(members.date_of_birth, 'dd.mm.yyyy') AS "Date of Birth", 
teams.title AS "Team", types.title AS "Type", leagues.title AS "Liga", sports.title AS "Sport"
FROM members_teams_types
JOIN members ON members_teams_types.member_id = members.id
LEFT JOIN teams ON members_teams_types.team_id = teams.id
LEFT JOIN types ON members_teams_types.type_id = types.id
LEFT JOIN leagues on teams.league_id = leagues.id
LEFT JOIN sports on leagues.sport_id = sports.id
ORDER BY teams.id, leagues.priority, sports.id;

SELECT matches.datetime, matches.is_homegame, teams.title AS "Team", matches.opponend, matches.result, 
venues.title AS "Venue", leagues.title AS "League"
FROM matches
LEFT JOIN venues ON matches.venue_id = venues.id
LEFT JOIN teams ON matches.team_id = teams.id
LEFT JOIN leagues ON teams.league_id = leagues.id
ORDER BY datetime, leagues.priority;

SELECT teams.title AS "Team", sponsors.title AS "Sponsor" FROM teams_sponsors
JOIN teams ON teams_sponsors.team_id = teams.id
JOIN sponsors ON teams_sponsors.sponsor_id = sponsors.id;



-- EXCEPTIONS ?

-- teams.sport_id muss ident zu leagues.sport_id sein
-- matches.result muss null sein wenn matches.datetime in der zukunft liegt
-- matches.result muss not null sein wenn matches.datetime in der vergangenheit liegt
